### ISSUE TITLE
Key error from headers

### ISSUE THREAD

**Issue by jmurrayufo** [jmurrayufo/poe_tracker#13]
```
2020-01-02 08:05:08,597 ERROR trade_loop.py:loop:60 Task threw exception
Traceback (most recent call last):
  File "/home/jmurray/Git/poe_tracker/poe_tracker/code/POE/trade/trade_loop.py", line 56, in loop
    r = queue_stash_task.result()
  File "/home/jmurray/Git/poe_tracker/poe_tracker/code/POE/trade/trade_loop.py", line 254, in queue_up_stashes
    async for data in x.iter_data():
  File "/home/jmurray/Git/poe_tracker/poe_tracker/code/POE/trade/api.py", line 89, in iter_data
    if not await self.pull_data():
  File "/home/jmurray/Git/poe_tracker/poe_tracker/code/POE/trade/api.py", line 57, in pull_data
    self.log.debug(r.headers['X-Rate-Limit-Ip'])
  File "/home/jmurray/.local/share/virtualenvs/poe_tracker-AjO3I1LM/lib/python3.7/site-packages/httpx/models.py", line 512, in __getitem__
    raise KeyError(key)
KeyError: 'X-Rate-Limit-Ip'
2020-01-02 08:05:08,599 INFO trade_loop.py:loop:61 Restarting queue_up_stashes
2020-01-02 08:05:08,599 INFO trade_loop.py:queue_up_stashes:244 Begin queue_up_stashes
2020-01-02 08:05:15,606 ERROR trade_loop.py:loop:60 Task threw exception
Traceback (most recent call last):
  File "/home/jmurray/Git/poe_tracker/poe_tracker/code/POE/trade/trade_loop.py", line 56, in loop
    r = queue_stash_task.result()
  File "/home/jmurray/Git/poe_tracker/poe_tracker/code/POE/trade/trade_loop.py", line 254, in queue_up_stashes
    async for data in x.iter_data():
  File "/home/jmurray/Git/poe_tracker/poe_tracker/code/POE/trade/api.py", line 89, in iter_data
    if not await self.pull_data():
  File "/home/jmurray/Git/poe_tracker/poe_tracker/code/POE/trade/api.py", line 57, in pull_data
    self.log.debug(r.headers['X-Rate-Limit-Ip'])
  File "/home/jmurray/.local/share/virtualenvs/poe_tracker-AjO3I1LM/lib/python3.7/site-packages/httpx/models.py", line 512, in __getitem__
    raise KeyError(key)
KeyError: 'X-Rate-Limit-Ip'
2020-01-02 08:05:15,607 INFO trade_loop.py:loop:61 Restarting queue_up_stashes
2020-01-02 08:05:15,607 INFO trade_loop.py:queue_up_stashes:244 Begin queue_up_stashes```

**Comment by jmurrayufo** [comment]
Added more logging, lets see what we capture
